export const FOCUSEDSEARCH='focusedSearch'
export const BLURSEARCH='blurSearch'
export const SHOWSEARCHLIST='showSearchList'
export const MOUSEENTER='mouseEnter'
export const MOUSELEAVE='mouseLeave'
export const NEXTPAGE='nextPage'
